Fix ATanH using wrong func in CORDIC
Rust 1.89.0 detects that `ATanH` is never constructed. func::ATan was being used rather than func::ATanH

error: struct `ATanH` is never constructed
   --> src/cordic.rs:466:16
    |
466 |     pub struct ATanH;
    |                ^^^^^
    |
    = note: `-D dead-code` implied by `-D warnings`
    = help: to override `-D warnings` add `#[allow(dead_code)]`

error: could not compile `stm32g4xx-hal` (lib) due to 1 previous error